# Generated by Django 4.2.1 on 2023-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod_blog', '0002_rename_body_post_content_remove_post_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
