# Generated by Django 4.2.1 on 2023-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod_blog', '0003_delete_post_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
