# Generated by Django 4.2.1 on 2023-05-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='libellai',
        ),
        migrations.AddField(
            model_name='detail',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artyprod.projet'),
        ),
        migrations.AddField(
            model_name='detail',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artyprod.service'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(to='artyprod.personnel'),
        ),
        migrations.AddField(
            model_name='projet',
            name='libelle',
            field=models.CharField(default='not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='projet',
            name='services',
            field=models.ManyToManyField(through='artyprod.Detail', to='artyprod.service'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fichier_CV',
            field=models.FileField(upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='lien_linkedIn',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projet',
            name='acheve',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
