# Generated by Django 4.2.1 on 2023-05-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0002_remove_equipe_membre_remove_projet_libellai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='libelle',
            new_name='libellai',
        ),
    ]
