# Generated by Django 4.2.1 on 2023-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0003_rename_libelle_projet_libellai'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='projet',
            name='acheve',
            field=models.BooleanField(default='False'),
        ),
    ]
