# Generated by Django 4.2.1 on 2023-05-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0005_delete_user_projet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='membres',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='projet',
        ),
        migrations.AddField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=255, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='equipe',
            name='personne',
            field=models.ManyToManyField(to='artyprod.personnel'),
        ),
    ]
