# Generated by Django 4.2.1 on 2023-05-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0007_remove_equipe_personne_equipe_membres_equipe_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='nom',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
