# Generated by Django 4.2.1 on 2023-05-13 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0009_alter_equipe_projet_alter_projet_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='equipe',
        ),
        migrations.AddField(
            model_name='projet',
            name='equipes_projet',
            field=models.ManyToManyField(related_name='projets', to='artyprod.equipe'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='projet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_projet', to='artyprod.projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
