# Generated by Django 4.2.1 on 2023-05-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0010_remove_projet_equipe_projet_equipes_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(related_name='equipes', to='artyprod.personnel'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='equipes_projet',
            field=models.ManyToManyField(blank=True, related_name='projets', to='artyprod.equipe'),
        ),
    ]
