# Generated by Django 4.2.1 on 2023-05-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0011_alter_equipe_membres_alter_projet_equipes_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='fichier',
        ),
    ]
