# Generated by Django 4.2.1 on 2023-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0015_alter_register_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
