# Generated by Django 4.2.1 on 2023-05-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0017_alter_register_options_alter_register_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
