# Generated by Django 4.2.1 on 2023-05-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0018_delete_register'),
    ]

    operations = [
    ]
